cart/urls.py
from django.urls import path

from cart import views

urlpatterns = [
    # 加入购物车
    path('add_cart/',views.add_cart, name='add_cart'),
    # 购物车数量的刷新
    path('cart_num/', views.cart_num, name='cart_num'),
    # 购物车
    path('cart/', views.cart, name='cart'),
    # 购物车价格
    path('cart_price/', views.cart_price, name='cart_price'),
#
    path('change_cart/',views.change_cart, name='change_cart'),
    path('del_cart/<int:id>/',views.del_cart, name='del_cart'),
    path('check_box/',views.check_box, name='check_box'),



]

fresh_shop/urls.py
from django.views.static import serve

from fresh_shop.settings import MEDIA_ROOT, MEDIA_URL, STATICFILES_DIRS
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path, include, re_path

from goods import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include(('cart.urls','cart'), namespace='cart')) ,
    path('order/', include(('order.urls','order'), namespace='order')),
    path('goods/', include(('goods.urls','goods'), namespace='goods')),
    path('user/', include(('user.urls','user'), namespace='user')),
    path('', views.index),
    re_path(r'^static/(?P<path>.*)$', serve, {"document_root": STATICFILES_DIRS[0]}),

    re_path(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
]

urlpatterns += static(MEDIA_URL,document_root=MEDIA_ROOT)

goods/urls.py
from django.urls import path

from goods import views

urlpatterns = [
    path('index/',views.index, name='index'),
    path('detail/',views.detail, name='detail'),
    path('by_price/',views.by_price, name='by_price'),
    path('by_click/',views.by_click, name='by_click'),
    path('list/',views.list, name='list'),
    path('search/',views.search, name='search'),
    path('detail/<int:id>/',views.detail,name='detail'),

]

order/urls.py
from django.urls import path

from order import views

urlpatterns = [
    path('place_order/',views.place_order, name='place_order'),
    path('order/',views.order, name='order'),
    path('user_order/', views.user_order, name='user_order'),

]

user/urls.py
from django.urls import path

from user import views

urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('user_site/', views.user_site, name='user_site'),
    path('user_info/', views.user_info, name='user_info'),

]

cart/models.py
from django.db import models

from goods.models import Goods
from user.models import User


class ShoppingCart(models.Model):
	"""
	购物车
	 """
	user = models.ForeignKey(User, verbose_name='用户', on_delete=models.CASCADE)
	goods = models.ForeignKey(Goods, verbose_name='商品', on_delete=models.CASCADE)
	nums = models.IntegerField(default=0, verbose_name='数量')
	add_time = models.DateTimeField(auto_now_add=True, verbose_name='添加时间')
	is_select = models.BooleanField(default=True)

	class Meta:
	    db_table = 'f_shopping_cart'

cart/views.py
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from cart.models import ShoppingCart
from goods.models import Goods


def add_cart(request):

    if request.method == 'POST':
        # 接收id和商品数量
        # 组装存储的商品格式[goods_id,num,is_select]
        # 组装多个商品格式:[[goods_id,num,is_select],[goods_id,num,is_select],]
        goods_id = int(request.POST.get('goods_id'))
        goods_num = int(request.POST.get('goods_num'))
        goods_list = [goods_id, goods_num, 1]
        session_goods = request.session.get('goods')

        if session_goods:
            # 1.有,则修改
            flag = True
            for se_goods in session_goods:
                if se_goods[0] == goods_id:
                    se_goods[1] = goods_num
                    print(se_goods)
                    # count = len(session_goods)
                    flag = False
            if flag:
                # 2.添加的商品不存在于购物车中,则新增
                session_goods.append(goods_list)
            request.session['goods'] = session_goods
            count = len(session_goods)

        else:
        #     第一次添加购物车
        # 需组装多个商品格式:[[goods_id,num,is_select],[goods_id,num,is_select],]
            request.session['goods'] = [goods_list]
            count = 1

        return JsonResponse({'code': 200, 'msg': '请求成功', 'count': count})


def cart_num(request):
    if request.method == 'GET':
        session_goods = request.session.get('goods')
        count = len(session_goods) if session_goods else 0
        return JsonResponse({'code': 200, 'msg': '请求成功', 'count': count})


def cart(request):
    if request.method == 'GET':
        session_goods = request.session.get('goods')
        # 返回格式:[objects1,objects2]
        # objects ===> [Goods Object, is_select,num,total_price]
        result = []
        if session_goods:
            for se_goods in session_goods:
                #     se_goods为[goods_id,num, is_select]
                goods = Goods.objects.filter(pk=se_goods[0]).first()
                total_price = goods.shop_price * se_goods[1]
                # print(se_goods[1],se_goods,total_price,goods)
                data = [goods, se_goods[1], se_goods[2], total_price]
                result.append(data)
        return render(request,'cart.html',{'result':result})


def cart_price(request):
    if request.method == 'GET':
        session_goods = request.session.get('goods')
        all_total = len(session_goods) if session_goods else 0
        all_price = 0
        is_select_num = 0
        selects = []
        for se_goods in session_goods:
            if se_goods[2]:
                goods = Goods.objects.filter(pk=se_goods[0]).first()
                all_price += goods.shop_price * se_goods[1]
                is_select_num += 1


        return JsonResponse({'code':200,'msg':'成功','all_total':all_total,
                             'all_price':all_price,'is_select_num':is_select_num,'selects':selects})

def check_box(request):
    if request.method == 'POST':
        session_goods = request.session.get('goods')
        id = request.POST.get('goods_id')
        check = request.POST.get('check')
        for se_goods in session_goods:
            if id:
                if se_goods[0] == int(id):
                    if se_goods[2]:
                        se_goods[2] = False
                    else:
                        se_goods[2] = True
            elif check == 'true':
                se_goods[2] = True
            else:
                se_goods[2] = False
            request.session['goods'] = session_goods
        return JsonResponse({'code':200, 'msg':'成功'})



def change_cart(request):
    if request.method == 'POST':
    #     #     修改商品数量和选择状态
    #     #     1.获取商品id和(数量或选择状态)
        goods_id = int(request.POST.get('goods_id'))
        # print(goods_id)
        goods_num = request.POST.get('goods_num')
        goods_select = request.POST.get('goods_select')
        # 2. 修改
        session_goods = request.session.get('goods')
        for se_goods in session_goods:
            if se_goods[0] == goods_id:
                se_goods[1] = int(goods_num) if goods_num else se_goods[1]
                se_goods[2] = int(goods_select) if goods_select else se_goods[2]
        request.session['goods'] = session_goods
        return JsonResponse({'code': 200, 'msg': '请求成功'})

def del_cart(request,id):

    if request.method == 'POST':

        session_goods = request.session.get('goods')
        for se_goods in session_goods:
            # se_goods为[goods_id,num, is_select]
            if se_goods[0] == id:
                session_goods.remove(se_goods)
                break
        request.session['goods'] = session_goods
        user_id = request.session.get('user_id')
        if user_id:
            ShoppingCart.objects.filter(goods_id=id).delete()
        return JsonResponse({'code': 200, 'msg': '请求成功'})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% block css %}
    {% endblock %}

    {% block js1 %}
    {% endblock %}
</head>
<body>
    {% block header %}
    {% endblock %}

    {% block search %}
    {% endblock %}

    {% block content %}
    {% endblock %}

    {% block footer %}
    {% endblock %}

    {% block js2 %}


    {% endblock %}
</body>
</html>

templates/base_main.html
{% extends 'base.html' %}

{% block css %}
    {% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
{% endblock %}

{% block js1 %}
    {% load static %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
{% endblock %}

{% block header %}
    <div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl" {% if user.id %} style="display:block;" {% endif %}>
					欢迎您：<em>{{ user.username }}</em>
					<span>|</span>
					<a href="{% url 'user:logout' %}">退出</a>
				</div>
				<div class="login_btn fl" {% if user.id %} style="display:none;" {% endif %}>
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'goods:index' %}">首页</a>
					<span>|</span>
					<a href="{% url 'user:user_info' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:cart' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'order:user_order' %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

{% block search %}
    <div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="search_con fl">
			<form method="post" action="/goods/search/">
				{% csrf_token %}
				<input type="text" class="input_text fl" name="search" placeholder="{{ key }}" value="">
				<input type="submit" class="input_btn fr" name="submit" value="搜索">
			</form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:cart' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">0</div>
		</div>
        <script>
            $.get('/cart/cart_num/', function(data){
                if(data.code == '200'){
                    $('#show_count').text(data.count)
                }
            })
        </script>
	</div>
{% endblock %}

{% block footer %}
    <div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
{% endblock %}

templates/base_user.html
<ul>
    <li><a href="{% url 'user:user_info' %}"{% if act1 %}class="active"{% endif %}>· 个人信息</a></li>
    <li><a href="{% url 'order:user_order' %}" {% if act2 %}class="active"{% endif %}>· 全部订单</a></li>
    <li><a href="{% url 'user:user_site' %}"{% if act3 %}class="active"{% endif %}>· 收货地址</a></li>
</ul>

templates/cart.html
{% extends 'base_main.html' %}

{% block title %}
    天天生鲜-购物车
{% endblock %}

{% block content %}
	<div class="total_count">全部商品<em>2</em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
    {% for goods in result %}
        <ul class="cart_list_td clearfix" id="goods_{{ goods.0.id }}">
            <li class="col01">
                <input type="checkbox" name="danxuan"  {% if goods.2 %} checked {% endif %} onclick="check_box({{goods.0.id}})">
            </li>
            <li class="col02"><img src="/media/{{ goods.0.goods_front_image }}"></li>
            <li class="col03" >{{ goods.0.name }}<br><em>{{ goods.0.shop_price }}元/500g</em></li>
            <li class="col04">500g</li>
            <li class="col05">{{ goods.0.shop_price}}元</li>
            <li class="col06">
                <div class="num_add">
                    <a href="javascript:;" class="add fl" onclick="add_cart({{ goods.0.id }},{{goods.0.shop_price}});"> + </a>
                    <input type="text" class="num_show fl" id="num_show_{{ goods.0.id }}" value="{{ goods.1 }}">
                    <a href="javascript:;" class="minus fl" onclick="sub_cart({{ goods.0.id }},{{goods.0.shop_price}})"> - </a>
                </div>
            </li>
            <li class="col07"><font id="num_{{ goods.0.id }}">{{ goods.3 }}</font>元</li>
            <li class="col08"><a href="javascript:;" onclick="del_cart({{ goods.0.id }})">删除</a></li>
        </ul>
    {% endfor %}

	<ul class="settlements">

		<li class="col01"><a href="" onclick="check_box('all')"><input type="checkbox" name="" ></a></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>0.00</em><br>共计<b>0</b>件商品</li>
		<li class="col04"><a href="{% url 'order:place_order' %}">去结算</a></li>
	</ul>

    {% csrf_token %}
    <script>
        dxs = $(':checkbox[name="danxuan"]')
        $('.settlements .col01 input').prop("checked", dxs.length == $(':checkbox[name=danxuan]:checked').length ? true : false)
        function check_box(id){
            <!--alert(id)-->
            var csrf = $('input[name="csrfmiddlewaretoken"]').val()
            check = $('.settlements .col01 input').prop('checked')
            <!--alert(check)-->
            if(id == 'all'){
                id = ''
                dxs = $(':checkbox[name="danxuan"]')

                    if(check){
                        $(':checkbox[name="danxuan"]').each(function(){ this.checked=true})
                    }else{
                    $(':checkbox[name="danxuan"]').each(function(){ this.checked=false})}

                <!--alert('===',id)-->
            }else{
                $('.settlements .col01 input').prop("checked", dxs.length == $(':checkbox[name=danxuan]:checked').length ? true : false)
            }
            $.ajax({
                url:'/cart/check_box/',
                type:'POST',
                data:{'goods_id':id,'check':check},
                headers:{'X-CSRFToken': csrf},
                dataType:'json',
                success:function(data){
                    cart_price()
                },
                error:function(data){
                    alert('失败')
                }
            })
        }

        <!--刷新价格,件数-->
        function cart_price(){
            $.get('/cart/cart_price/', function(data){
                if(data.code == '200'){
                    $('.total_count em').html(data.all_total)
                    $('.settlements .col03 em').html(data.all_price)
                    $('.settlements .col03 b').html(data.is_select_num)

                }
            })
        }
        cart_price()

        <!--添加商品数量-->
        function add_cart(id,shop_price){

            var num = $('#num_show_' + id).val()
            var new_num = parseInt(num) + 1
            $('#num_show_'+id).val(new_num)
            $('#num_'+id).text(new_num * shop_price)
            change_cart(id, new_num)
        }
        <!--减少商品数量-->
        function sub_cart(id, shop_price){
            var num = $('#num_show_' + id).val()
            if(parseInt(num) > 1){
                var new_num = parseInt(num) - 1
                $('#num_show_' + id).val(new_num)

                $('#num_'+id).text(new_num * shop_price)
                change_cart(id, new_num)
            }
        }

        <!--修改数量或选择状态-->
        function change_cart(id, new_num){
            var csrf = $('input[name="csrfmiddlewaretoken"]').val()
            $.ajax({
                url:'/cart/change_cart/',
                type:'POST',
                data:{'goods_id':id, 'goods_num': new_num},
                headers:{'X-CSRFToken': csrf},
                dataType:'json',
                success:function(data){
                    <!--刷新数量,总价,件数-->
                    cart_price()
                },
                error:function(data){
                    alert('失败')
                }
            })
        }

        function del_cart(id){
             var csrf = $('input[name="csrfmiddlewaretoken"]').val()
             $.ajax({
                url:'/cart/del_cart/'+ id + '/',
                type:'POST',

                headers:{'X-CSRFToken': csrf},
                dataType:'json',
                success:function(data){
                    console.log(data)
                    <!--刷新页面-->
                    <!--location.href='/cart/cart'-->
                    location.reload()
                    <!--局部刷新-->
                    <!--$('#goods_'+ id).remove()-->
                },
                error:function(data){
                    alert('失败')
                }
            })
        }


    </script>
{% endblock %}

templates/index.html
{% extends 'base_main.html' %}

{% block title %}
    天天生鲜-首页
{% endblock %}

{% block js1 %}
    {{ block.super }}
	<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/static/js/slide.js"></script>
{% endblock %}

{% block content %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			<li><a href="#model01" class="fruit">新鲜水果</a></li>
			<li><a href="#model02" class="seafood">海鲜水产</a></li>
			<li><a href="#model03" class="meet">猪牛羊肉</a></li>
			<li><a href="#model04" class="egg">禽类蛋品</a></li>
			<li><a href="#model05" class="vegetables">新鲜蔬菜</a></li>
			<li><a href="#model06" class="ice">速冻食品</a></li>
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="/static/images/slide.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide02.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide03.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide04.jpg" alt="幻灯片"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="/static/images/adv01.jpg"></a>
			<a href="#"><img src="/static/images/adv02.jpg"></a>
		</div>
	</div>
    {% for data in result %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">
                {% for type in category_type %}
                    {% if type.0 == data.0.category_type %}
                        {{ type.1 }}
                    {% endif %}
                {% endfor %}
            </h3>
			<div class="subtitle fl">
			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/media/{{ data.0.category_front_image }}"></div>
			<ul class="goods_list fl">
                {% for i in data.1  %}
                    <li>
                        <h4><a href="{% url 'goods:detail' i.id %}">{{ i.name }}</a></h4>
                        <a href="{% url 'goods:detail' i.id %}"><img src="/media/{{ i.goods_front_image }}"></a>
                        <div class="prize">¥ {{ i.shop_price }}</div>
                    </li>
                {% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}

{% endblock %}

{% block js2 %}
	<script type="text/javascript" src="/static/js/slide.js"></script>
	<script type="text/javascript">
		<!--BCSlideshow('focuspic');-->
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>
{% endblock %}

templates/list.html
{% extends 'base_main.html' %}



 {% block content %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					<li><a href="#" class="fruit">新鲜水果</a></li>
					<li><a href="#" class="seafood">海鲜水产</a></li>
					<li><a href="#" class="meet">猪牛羊肉</a></li>
					<li><a href="#" class="egg">禽类蛋品</a></li>
					<li><a href="#" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="#" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">新鲜水果</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					<li>
						<a href="#"><img src="/static/images/goods/goods001.jpg"></a>
						<h4><a href="#">进口柠檬</a></h4>
						<div class="prize">￥3.90</div>
					</li>
					<li>
						<a href="#"><img src="/static/images/goods/goods002.jpg"></a>
						<h4><a href="#">玫瑰香葡萄</a></h4>
						<div class="prize">￥16.80</div>
					</li>
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:list'%}" {% if act or act1 %}class="active"{% endif %}>默认</a>
				<a href="{% url 'goods:by_price' %}" {% if act2 %}class="active"{% endif %} >价格</a>
				<a href="{% url 'goods:by_click' %}" {% if act3 %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
				{% for good in goods %}
				<li>
					<a href="{% url 'goods:detail' good.id %}"><img src="/media/{{ good.goods_front_image }}"></a>
					<h4><a href="{% url 'goods:detail' good.id %}">{{ good.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ good.shop_price }}</span>
						<span class="unit">{{ good.shop_price }}/500g</span>
						<a href="{% url 'goods:detail' good.id %}" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
				{% endfor %}

			</ul>

			<div class="pagenation">
				{% if goods.has_previous %}
					{% if act %}<a href="{% url 'goods:list' %}?page={{ goods.previous_page_number }}">{% endif %}
					{% if act1 %}<a href="{% url 'goods:search' %}?page={{ goods.previous_page_number }}">{% endif %}
					{% if act2 %}<a href="{% url 'goods:by_price' %}?page={{ goods.previous_page_number }}">{% endif %}
					{% if act3 %}<a href="{% url 'goods:by_click' %}?page={{ goods.previous_page_number }}">{% endif %}
						<上一页
					</a>
					{% endif %}
					{% for i in goods.paginator.page_range %}
					{% if act %}<a href="{% url 'goods:list' %}?page={{ i }}" class="active">{{ i }}</a>{% endif %}
					{% if act1 %}<a href="{% url 'goods:search' %}?page={{ i }}" class="active">{{ i }}</a>{% endif %}
					{% if act2 %}<a href="{% url 'goods:by_price' %}?page={{ i }}" class="active">{{ i }}</a>{% endif %}
					{% if act3 %}<a href="{% url 'goods:by_click' %}?page={{ i }}" class="active">{{ i }}</a>{% endif %}
					{% endfor %}
					{% if goods.has_next %}
					{% if act %}<a href="{% url 'goods:list' %}?page={{ goods.next_page_number }}">{% endif %}
					{% if act1 %}<a href="{% url 'goods:search' %}?page={{ goods.next_page_number }}">{% endif %}
					{% if act2 %}<a href="{% url 'goods:by_price' %}?page={{ goods.next_page_number }}">{% endif %}
					{% if act3 %}<a href="{% url 'goods:by_click' %}?page={{ goods.next_page_number }}">{% endif %}
						下一页>
					</a>
					{% endif %}

			</div>
		</div>



	</div>
{% endblock %}

templates/login.html
{% extends 'base_main.html' %}
{% block title %}
	天天生鲜-登录
{% endblock %}


<body>
{% block content %}
	<!--<div class="login_top clearfix">-->
		<!--<a href="index.html" class="login_logo"><img src="/static/images/logo02.png"></a>-->
	<!--</div>-->

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="#">立即注册</a>
				</div>
				<div class="form_input">
					<form action="" method="post">
						{% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名">
						<div class="user_error">{{ errors.username}}</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">{{ errors.pwd }}</div>
						<div class="more_input clearfix">

						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/user_center_info.html
{% extends 'base_main.html' %}

{% block title %}
    天天生鲜-用户中心
{% endblock %}

{% block search %}

	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>
{% endblock %}
{% block content %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			{% include 'base_user.html' %}
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>sadcsa</li>
							<li><span>联系方式：</span>182102545245</li>
							<li><span>联系地址：</span>成都市武侯区</li>
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
				{% for br in brs %}
				<li>
					<a href="{% url 'goods:detail' br.br.id %}"><img src="/media/{{ br.br.goods_front_image}}"></a>
					<h4><a href="{% url 'goods:detail' br.br.id %}">{{ br.br.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ br.br.shop_price }}</span>
						<span class="unit">{{ br.br.shop_price }}/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
				{% endfor %}

			</ul>
		</div>
		</div>
	</div>
{% endblock %}